<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Файл">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Документ">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="СвНП">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="НаимОрг" type="xs:string"/>
                    <xs:element name="ИНН" type="xs:string"/>
                    <xs:element name="КПП" type="xs:string" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="ПерсСвФЛ" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Фамилия" type="xs:string"/>
                    <xs:element name="Имя" type="xs:string"/>
                    <xs:element name="Отчество" type="xs:string" minOccurs="0"/>
                  </xs:sequence>
                  <xs:attribute name="ИННФЛ" type="xs:string" use="required"/>
                  <xs:attribute name="СНИЛС" type="xs:string" use="required"/>
                  <xs:attribute name="СумВыпл" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="КНД" type="xs:string" use="required"/>
            <xs:attribute name="ДатаДок" type="xs:string" use="required"/>
            <xs:attribute name="Период" type="xs:string" use="required"/>
            <xs:attribute name="ОтчетГод" type="xs:string" use="required"/>
            <xs:attribute name="КодНО" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="ИдФайл" type="xs:string" use="required"/>
      <xs:attribute name="ВерсПрог" type="xs:string" use="required"/>
      <xs:attribute name="ВерсФорм" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
